- name: Install infra-imagemagick-server
  hosts: infra-imagemagick-server

  tasks:
    - name: Common | Add authorized_keys for Ubuntu user
      authorized_key: user=ubuntu key="{{ lookup('file', 'templates/christy-dsa.pub') }}"

    - name: Common | Gather EC2 facts
      action: ec2_facts

    - name: Common | Add US APT Mirrors
      action: template src=templates/sources.list dest=/etc/apt/sources.list
      register: apt_sources

    - name: Common | Update APT
      apt: upgrade=dist cache_valid_time=3600 update_cache=yes dpkg_options='force-confold,force-confdef'
      when: apt_sources|changed

    - name: Common | Install Packages
      apt: pkg={{ item }} state=present
      with_items:
        - apache2
        - apg
        - build-essential
        - curl
        - git-core
        - htop
        - iotop
        - libpcre3
        - logtail
        - mlocate
        - mtr
        - mysql-client
        - phpbb3
        - psmisc
        - vsftpd
        - telnet
        - vim
        - wget

    - name: Common | Add convenience shortcut wtf
      action: lineinfile dest=/home/ubuntu/.bashrc line="alias wtf='sudo tail -f /var/log/*{log,err} /var/log/{dmesg,messages,*{,/*}{log,err}}'"

    - name: Web | Add webdev user for uploading www files
      user: name=webdev home=/var/www shell=/bin/bash comment="User for uploading www files" group=www-data password={{ lookup('env','IIM_FTP_PASS_ENC') }}

    - name: Web | Create webroot
      file: path=/var/www state=directory owner=webdev group=www-data mode=0775 recurse=yes

    - name: FTP | Write config
      action: template src=templates/vsftpd.conf dest=/etc/vsftpd.conf
      register: vsftp_conf

    - name: FTP | Restart
      action: service name=vsftpd state=restarted
      when: vsftp_conf|changed

    - name: Building ImageMagick | Dev Packges
      apt: pkg={{ item }} state=present
      with_items:
        - apache2
        - fftw-dev
        - libdjvulibre-dev
        - libfontconfig-dev
        - libfreetype6-dev
        - libgs-dev
        - libjpeg-dev
        - liblcms-dev
        - liblqr-dev
        - liblzma-dev
        - libopenexr-dev
        - libpango1.0-dev
        - libpng-dev
        - librsvg2-dev
        - libtiff-dev
        - libwebp-dev
        - libwmf-dev
        - libxml2-dev

    - name: Content | Fetch (patience)
      script: scripts/content-fetch.sh > /tmp/content-fetch.log
      tags: fetch
