- name: Install infra-imagemagick-server
  hosts: infra-imagemagick-server

  tasks:
    - name: Access | Add authorized_keys for user ubuntu
      authorized_key: user=ubuntu key="{{ lookup('file', 'templates/cristy-dsa.pub.j2') }}"

    - name: Access | Add user cristy
      user: name=cristy home=/home/cristy shell=/bin/bash comment="Cristy" group=www-data

    - name: Access | Add authorized_keys for user cristy
      authorized_key: user=cristy key="{{ lookup('file', 'templates/cristy-dsa.pub.j2') }}"

    - name: Common | Gather EC2 facts
      action: ec2_facts

    - name: Common | Add US APT Mirrors
      action: template src=templates/sources.list.j2 dest=/etc/apt/sources.list
      register: apt_sources

    - name: Common | Update APT
      apt: upgrade=dist cache_valid_time=3600 update_cache=yes dpkg_options='force-confold,force-confdef'
      when: apt_sources|changed

    - name: Common | Install Packages
      apt: pkg={{ item }} state=present
      with_items:
        - apache2
        - apt-file
        - apg
        - build-essential
        - curl
        - git-core
        - htop
        - iotop
        - libpcre3
        - logtail
        - mlocate
        - mtr
        - mysql-client
        - phpbb3
        - psmisc
        - vsftpd
        - telnet
        - vim
        - wget

    - name: Common | Add convenience shortcut wtf
      action: lineinfile dest=/home/ubuntu/.bashrc line="alias wtf='sudo tail -f /var/log/*{log,err} /var/log/{dmesg,messages,*{,/*}{log,err}}'"

    - name: Web | Add webdev user for uploading www files
      user: name=webdev home=/var/www shell=/bin/bash comment="User for uploading www files" group=www-data password={{ lookup('env','IIM_FTP_PASS_ENC') }}

    - name: Web | Create webroot
      file: path=/var/www state=directory owner=webdev group=www-data mode=0775 recurse=yes

    - name: FTP | Write config
      action: template src=templates/vsftpd.conf.j2 dest=/etc/vsftpd.conf
      register: vsftp_conf

    - name: FTP | Restart
      action: service name=vsftpd state=restarted
      when: vsftp_conf|changed

    - name: ImageMagick Development | Dev Packges
      apt: pkg={{ item }} state=present
      with_items:
        - cpanminus
        - fftw-dev
        - libdjvulibre-dev
        - libfontconfig-dev
        - libfreetype6-dev
        - libgs-dev
        - libjpeg-dev
        - liblcms-dev
        - libperl-dev
        - liblqr-dev
        - liblzma-dev
        - libopenexr-dev
        - libpango1.0-dev
        - libpng-dev
        - librsvg2-dev
        - libtiff-dev
        - libwebp-dev
        - libwmf-dev
        - libxml2-dev

    - name: ImageMagick Development | Perl Modules
      cpanm: name={{ item }} notest=True
      with_items:
        - Image::Magick
        - Digest::SHA3

    - name: Content | Upload Daily Mirror script
      copy: src=scripts/content-fetch.sh dest=/home/ubuntu/content-fetch.sh mode=0755 owner=ubuntu group=ubuntu
      tags: content

    - name: Content | Touch log of Daily Mirror script
      file: path=/var/log/content-fetch.log state=touch owner=ubuntu group=ubuntu mode=644
      tags: content

    - name: Content | Install Daily Mirror script crontab
      cron: name="Daily mirror" user="ubuntu" minute="0" hour="1" job="/home/ubuntu/content-fetch.sh > /var/log/content-fetch.log 2>&1"
      tags: content
